Updating Grafana Agent Buildpack
- Adding default agent config.yml
- Adds background execution script
- Updates README with config details
- Updates to compile script
--- Parameterize the Agent version
--- Uses default config.yml unless one present in application
--- Exports all env vars for agent to substitute when executed
--- Drops background execution script into .profile.d

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,30 +1,75 @@
-#!/bin/sh
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir> <env-dir>
 
+# Fail fast
+set -e
+set -o pipefail
+
+# Debug
+#set -x
+
+# Export environment variables from directory
+# https://devcenter.heroku.com/articles/buildpack-api#bin-compile-summary
+export_env_dir() {
+  env_dir=$1
+  acceptlist_regex=${2:-''}
+  denylist_regex=${3:-''}
+  if [ -d "$env_dir" ]; then
+    for e in $(ls $env_dir); do
+      echo "$e" | grep -E "$acceptlist_regex" | grep -qvE "$denylist_regex" &&
+      export "$e=$(cat $env_dir/$e)"
+      :
+    done
+  fi
+}
+
+# Parse params
 BUILD_DIR=$1
 CACHE_DIR=$2
+ENV_DIR=$3
+BUILDPACK_DIR=$(cd "$(dirname "$0")"; cd ..; pwd)
 
-mkdir -p $BUILD_DIR/bin
+# Load formating tools
+source "$BUILDPACK_DIR/bin/common.sh"
 
-if [[ -f $CACHE_DIR/agent-linux-amd64 && cmp -s $BUILD_DIR/bin/agent $CACHE_DIR/agent-linux-amd64 ]]; then
-  echo "Reusing cached agent binary."
-  cp -f "$CACHE_DIR/agent" "$BUILD_DIR/bin/agent"
+logger "Grafana Agent Buildpack"
+
+
+APP_CONFIG_FILE_PATH="$BUILD_DIR/grafana-agent/config.yml"
+DEFAULT_CONFIG_FILE_PATH="$BUILDPACK_DIR/config/grafana-agent-config.yml"
+# Source config file from build pack unless the app provides one
+if [ -f "$APP_CONFIG_FILE_PATH" ]; then
+  CONFIG_FILE_PATH="$APP_CONFIG_FILE_PATH"
+  logger "Using application provided Grafana Agent config ($APP_CONFIG_FILE_PATH)."
 else
-  echo "Downloading agent binary."
-  curl -o "$CACHE_DIR/agent-linux-amd64.zip" -L "https://github.com/grafana/agent/releases/download/v0.15.0/agent-linux-amd64.zip"
-  unzip agent-linux-amd64.zip -d $CACHE_DIR
-  cp -f "$CACHE_DIR/agent-linux-amd64" "$BUILD_DIR/bin/agent"
+  CONFIG_FILE_PATH="$DEFAULT_CONFIG_FILE_PATH"
+  logger "No Grafana Agent config provide by the application..."
+  logger "Using the default config provided by the buildpack ($DEFAULT_CONFIG_FILE_PATH)."
 fi
 
-if [[ -f $CACHE_DIR/agent.yml && cmp -s $BUILD_DIR/config.yml $CACHE_DIR/agent.yml ]]; then
-  echo "Reusing cached config.yml."
-  cp -f "$CACHE_DIR/agent.yml" "$BUILD_DIR/agent.yml"
-else
-  if ! [ -x "$(command -v envsubst)" ]; then
-    echo "Installing dependencies."
-    apt install -y gettext
-  fi
-
-  echo "Substituting envrionment variables."
-  envsubst < $BUILD_DIR/config.yml > $BUILD_DIR/agent.yml
-  cp -f "$BUILD_DIR/agent.yml" "$CACHE_DIR/agent.yml"
+# Determine the Grafana Agent version to use
+if [ -f "$ENV_DIR/GRAFANA_AGENT_VERSION" ]; then
+  GRAFANA_AGENT_VERSION=$(cat $ENV_DIR/GRAFANA_AGENT_VERSION)
 fi
+
+AGENT_VERSION="${GRAFANA_AGENT_VERSION:-v0.28.0}"
+
+# TODO - Use $CACHE_DIR to cache the agent binary
+logger "Downloading Grafana Agent $AGENT_VERSION..."
+rm -rf "$CACHE_DIR/$AGENT_VERSION/agent-linux-amd64"
+mkdir -p "$CACHE_DIR/$AGENT_VERSION"
+curl -o "$CACHE_DIR/$AGENT_VERSION/agent-linux-amd64.zip" -L "https://github.com/grafana/agent/releases/download/$AGENT_VERSION/agent-linux-amd64.zip" --silent | indent
+unzip "$CACHE_DIR/$AGENT_VERSION/agent-linux-amd64.zip" -d "$CACHE_DIR/$AGENT_VERSION" | indent
+mkdir -p "$BUILD_DIR/bin"
+cp -f "$CACHE_DIR/$AGENT_VERSION/agent-linux-amd64" "$BUILD_DIR/bin/agent"
+rm "$CACHE_DIR/$AGENT_VERSION/agent-linux-amd64.zip"
+
+# Export env vars
+logger "Exporting Env vars..."
+export_env_dir "$ENV_DIR"
+cp "$CONFIG_FILE_PATH" "$BUILD_DIR/agent.yml"
+
+# Write start script to .profile.d
+mkdir -p "$BUILD_DIR/.profile.d"
+cp "$BUILDPACK_DIR/extras/grafana-agent-buildpack.sh" "$BUILD_DIR/.profile.d/"
+chmod +x "$BUILD_DIR/.profile.d/grafana-agent-buildpack.sh"
